enum {
    ID_VERSION_INFO = 1,

    ID_NEW_GAME,
    ID_NEW_PERIOD,

    ID_CLOCK_TIMER,

    ID_TOGGLE_PLAY,
    ID_PLAY_GAME,
    ID_PAUSE_GAME,
	ID_SET_GAME_CLOCK,
	ID_INCR_GAME_CLOCK,
	ID_DECR_GAME_CLOCK,
    ID_RESET_SHOT_CLOCK,
    ID_INCR_SHOT_CLOCK,
	ID_DECR_SHOT_CLOCK,

    ID_INCR_LEFT_SCORE,
    ID_DECR_LEFT_SCORE,

    ID_INCR_RIGHT_SCORE,
    ID_DECR_RIGHT_SCORE,

    ID_INCR_LEFT_FOUL,
    ID_DECR_LEFT_FOUL,

    ID_INCR_RIGHT_FOUL,
    ID_DECR_RIGHT_FOUL,

    ID_INCR_PERIOD,
    ID_DECR_PERIOD,

    ID_PERIOD_LENGTH_TEXT,
    ID_SHOT_CLOCK_TEXT,

    ID_GAME_CLOCK_TEXT,
};
